export const PRIVY_APP_ID = '{PRIVY_APP_ID_THERE}';
export const PRIVY_APP_SECRET = '{PRIVATE_APP_SECRET_THERE}';
export const RELAYER_PRIVATE_KEY = '{RELAYER_PRIVATE_KEY_THERE}';
export const RELAYER_ADDRESS = '{RELAYER_ADDRESS_HERE}';
export const ALCHEMY_API_TOKEN = '{ALCHEMY_API_TOKEN}';
